In [1]:
import numpy as np

In [2]:
a=np.array([(1,2,3),(2,3,4),(3,4,5)])

In [3]:
a.dtype

dtype('int32')

In [4]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [5]:
a+a

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [6]:
a*a

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [ 9, 16, 25]])

In [9]:
a=a/a

In [10]:
a.dtype

dtype('float64')

In [11]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
